### ISSUE TITLE
Forsørgeransvar LibFigFilTypr:R

### ISSUE THREAD

**Issue by areedv** [Rapporteket/rapsodi#1]
som muligens forsvinner ut av rapbase...

**Comment by lenaringstado** [comment]
Vi er enige om at denne funksjonen kan legges i den planlagte pakken som lyder et navn som ligner på rapfigurer. På sikt ønsker vi å fase funksjonen helt ut. Inntil videre vedlikeholdes den ved behov av @kevinthon og @lenaringstado.
